#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browsers
browser = chrome

#Credentials
username = admin
password = admin123

#implicitWait in seconds
implicitWait = 10

#ExplicitWait in seconds
ExplicitWait = 30